{% set name = "aiida-cp2k" %}
{% set version = "2.0.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/aiida-cp2k-{{ version }}.tar.gz
  sha256: d6735abcbc0d83b068c26b8c407514c37d4a4e99ee7d7c6ec90382ac1012bd6a

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 1

requirements:
  host:
    - python >=3.8
    - flit-core >=3.2,<4
    - pip
  run:
    - python >=3.8
    - aiida-core >=2.0.0,<3.0.0
    - aiida-gaussian-datatypes
    - ase
    - ruamel.yaml >=0.16.5
    - cp2k-output-tools

test:
  imports:
    - aiida_cp2k
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/aiidateam/aiida-cp2k
  summary: The official AiiDA plugin for CP2K.
  license: MIT
  license_file: LICENSE.txt

extra:
  recipe-maintainers:
    - chrisjsewell
